"""baseline

Revision ID: 0001_baseline
Revises:
Create Date: 2026-05-06 00:00:00.000000

This is the baseline migration. It intentionally does nothing.

Why: existing databases were created via `schema_sync.py` (the legacy bootstrap
path) before Alembic was introduced. Stamping such a database with this
revision (`alembic stamp 0001_baseline`) brings it under Alembic control
without altering its schema. Subsequent migrations then apply normally on top.

For a fresh database with no tables, run `alembic upgrade head` after
ensuring `schema_sync` has run at least once at startup, OR replace this
baseline with an autogenerated one (`alembic revision --autogenerate
-m "initial"`) and remove `schema_sync.py` entirely.
"""
from __future__ import annotations

from typing import Sequence, Union


revision: str = "0001_baseline"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
