/** @type {import('tailwindcss').Config} */
export default {
    content: ["./index.html", "./src/**/*.{ts,tsx}"],
    theme: {
        extend: {
            colors: {
                "on-secondary-container": "#61615d",
                "inverse-on-surface": "#f3f0eb",
                "secondary": "#5e5f5b",
                "error": "#ba1a1a",
                "on-tertiary-container": "#b2755b",
                "secondary-fixed-dim": "#c7c6c2",
                "on-secondary": "#ffffff",
                "outline-variant": "#c4c6cf",
                "surface-container-lowest": "#ffffff",
                "inverse-primary": "#b1c7f2",
                "on-error-container": "#93000a",
                "on-primary": "#ffffff",
                "background": "#fbf9f4",
                "tertiary-fixed-dim": "#fdb698",
                "tertiary": "#000000",
                "surface-container": "#f0eee9",
                "primary-fixed-dim": "#b1c7f2",
                "primary-container": "#001b3d",
                "on-tertiary-fixed-variant": "#6b3a24",
                "on-secondary-fixed-variant": "#464743",
                "on-tertiary": "#ffffff",
                "surface": "#fbf9f4",
                "error-container": "#ffdad6",
                "on-background": "#1b1c19",
                "on-surface": "#1b1c19",
                "on-primary-container": "#6f84ac",
                "surface-tint": "#495f84",
                "surface-container-high": "#eae8e3",
                "primary-fixed": "#d6e3ff",
                "inverse-surface": "#30312d",
                "tertiary-fixed": "#ffdbcd",
                "surface-container-low": "#f6f3ee",
                "tertiary-container": "#351001",
                "outline": "#74777f",
                "on-error": "#ffffff",
                "primary": "#000000",
                "on-surface-variant": "#44474e",
                "surface-container-highest": "#e4e2dd",
                "surface-bright": "#fbf9f4",
                "on-secondary-fixed": "#1b1c19",
                "surface-dim": "#dcdad5",
                "on-primary-fixed-variant": "#31476b",
                "secondary-fixed": "#e4e2dd",
                "on-primary-fixed": "#001b3d",
                "surface-variant": "#e4e2dd",
                "secondary-container": "#deddd8",
                "on-tertiary-fixed": "#351001",
                "navy": "#001b3d",
                "warn-bg": "#fef3c7",
                "warn-fg": "#92400e",
                "err-bg": "#fceeed",
            },
            borderRadius: {
                DEFAULT: "0.125rem",
                lg: "0.25rem",
                xl: "0.5rem",
                full: "0.75rem",
                pill: "9999px",
            },
            spacing: {
                xs: "4px",
                sm: "8px",
                md: "16px",
                lg: "24px",
                xl: "32px",
                base: "4px",
                "topbar-height": "56px",
                "sidebar-width": "240px",
            },
            fontFamily: {
                "body-md": ["Inter", "system-ui", "sans-serif"],
                "body-sm": ["Inter", "system-ui", "sans-serif"],
                "table-data": ["Inter", "system-ui", "sans-serif"],
                "display-title": ['"Playfair Display"', "serif"],
                "section-header": ["Inter", "system-ui", "sans-serif"],
                "page-header": ['"Playfair Display"', "serif"],
                "label-caps": ["Inter", "system-ui", "sans-serif"],
            },
            fontSize: {
                "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
                "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
                "table-data": ["13px", { lineHeight: "16px", fontWeight: "400" }],
                "display-title": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
                "section-header": ["16px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
                "page-header": ["24px", { lineHeight: "1.3", fontWeight: "600" }],
                "label-caps": ["11px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
            },
            keyframes: {
                "toast-in": {
                    from: { opacity: "0", transform: "translateY(10px) scale(0.97)" },
                    to: { opacity: "1", transform: "translateY(0) scale(1)" },
                },
            },
            animation: {
                "toast-in": "toast-in 220ms cubic-bezier(0.22, 1, 0.36, 1) both",
            },
        },
    },
    plugins: [],
};
