"""Phase B — Copilot trace persistence.

One row per orchestrator run (per ``request_id`` / ``call_id``). Stores the
reasoning trail: orchestrator decision \u2192 big agent \u2192 mini agents \u2192 verifier.
"""

from __future__ import annotations

from sqlalchemy import Column, DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.sql import func

from backend.database.database import Base


class CopilotTrace(Base):
    __tablename__ = "copilot_traces"

    id = Column(Integer, primary_key=True, index=True)

    # Stable UUID generated by the orchestrator (== state["request_id"]).
    call_id = Column(String(64), nullable=False, unique=True, index=True)

    tenant_id = Column(Integer, ForeignKey("tenants.id", ondelete="CASCADE"), nullable=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id", ondelete="SET NULL"), nullable=True, index=True)
    case_id = Column(Integer, ForeignKey("cases.id", ondelete="SET NULL"), nullable=True, index=True)
    document_id = Column(Integer, ForeignKey("documents.id", ondelete="SET NULL"), nullable=True, index=True)

    # Routing & decisions
    intent = Column(String(128), nullable=True, index=True)
    big_agent = Column(String(64), nullable=True, index=True)
    route = Column(String(64), nullable=True, index=True)
    mode = Column(String(64), nullable=True)
    effective_mode = Column(String(64), nullable=True)

    # Outcome
    verdict = Column(String(64), nullable=True, index=True)  # verified | partial | unverified | refused | error
    confidence = Column(String(32), nullable=True)
    used_fallback = Column(Integer, nullable=True)  # 0/1
    error_count = Column(Integer, nullable=False, default=0)

    duration_ms = Column(Integer, nullable=True)

    # JSON-serialised arrays / payloads (Text for cross-DB compat).
    mini_agents_used_json = Column(Text, nullable=True)  # list[str]
    stages_json = Column(Text, nullable=True)            # list[{name,status,detail,metadata}]
    metadata_json = Column(Text, nullable=True)          # free-form bag

    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        index=True,
    )
