"""Convert reranker_triples.parquet → reranker_pairs.csv for the Colab notebook.

Reads the 37K-row parquet generated by scripts/generate_reranker_dataset.py
and emits the column layout the training notebook expects:
    query_id, query, candidate_text, label, source, query_language, passage_country, passage_code_family
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PARQUET = ROOT / "data" / "training" / "reranker_triples.parquet"
OUT_CSV = ROOT / "docs" / "ml" / "data" / "reranker_pairs.csv"


def main() -> None:
    if not PARQUET.exists():
        sys.exit(f"missing input: {PARQUET}")

    df = pd.read_parquet(PARQUET)
    print(f"loaded {len(df):,} rows from {PARQUET.name}")
    print(f"columns: {list(df.columns)}")

    df = df.rename(columns={"passage": "candidate_text"})
    df["query_id"] = "q_" + df.groupby("query").ngroup().astype(str).str.zfill(6)
    df["source"] = "ollama_llama31_8b"

    keep = [
        "query_id", "query", "candidate_text", "label",
        "source", "query_language", "passage_country", "passage_code_family",
    ]
    keep = [c for c in keep if c in df.columns]
    df = df[keep]

    OUT_CSV.parent.mkdir(parents=True, exist_ok=True)
    df.to_csv(OUT_CSV, index=False)

    size_mb = OUT_CSV.stat().st_size / 1024 / 1024
    print(f"wrote {len(df):,} rows -> {OUT_CSV} ({size_mb:.1f} MB)")
    print(f"unique queries: {df['query_id'].nunique():,}")
    print(f"label distribution:\n{df['label'].value_counts()}")


if __name__ == "__main__":
    main()
